GET http://localhost:3000/public HTTP/1.1

###
GET http://localhost:3000/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjAzNDEzMTIsInVzZXJfaWQiOjJ9.mxWVpKTfoy5F7vd8tBpl59IcIf7aejIkZ0tCE-_Xe7g

###
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "janedoe@gmail.com",
    "password": "Jane@1234"
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "janedoe@gmail.com",
    "password": "Jane@1234"
}